### ISSUE TITLE
Use under Windows

### ISSUE THREAD

**Issue by neclepsio** [RadhiFadlillah/qamel#1]
After some troubles, I got it run under Windows 7 and amd64.

I already installed mingw64 along with its Qt5 package and configured it to build for go-qml.

The problem I run into was this error during compiling:

    Failed to build app: exit status 2
    # github.com/RadhiFadlillah/qamel
    cannot parse gcc output $WORK\b002\\_cgo_.o as ELF, Mach-O, PE object

This is related to https://github.com/golang/go/issues/24341: Go is unable to use big-obj files. After some research I found out that the flag to use them is added from `qmake` itself. The only way I found to work-around this was to remove ` -Wa,-mbig-obj` from `QMAKE_CFLAGS` line of `[...]\msys64\mingw64\share\qt5\mkspecs\win32-g++\qmake.conf`.

Maybe can Qamel be modified so that it solves this into the  `.pro` file? I couln't find any way, but I never used `qmake` before. 

A quick search into https://github.com/therecipe/qt shows that it solves the same problem here: https://github.com/therecipe/qt/blob/master/internal/binding/templater/template_cgo_qmake.go#L575.

After this, I have been able to compile and test the examples, finding no issues.

I made a hack (and relative pull request) in the style of https://github.com/therecipe/qt.

**Comment by RadhiFadlillah** [comment]
Hi @neclepsio, sorry for late reply.

Thanks for the PR. I've merged it, so I will close this issue.
