### ISSUE TITLE
go get github.com/RadhiFadlillah/qamel/qamel: no matching versions for query "latest"

### ISSUE THREAD

**Issue by MostHated** [RadhiFadlillah/qamel#12]
Hey there,
    I tried to follow the install instructions but when I run:

```
 go get -u -v github.com/RadhiFadlillah/qamel/qamel   
```
I get the following error:
```
go: finding github.com/RadhiFadlillah/qamel/qamel latest
go: finding github.com/RadhiFadlillah/qamel latest
Fetching https://github.com?go-get=1
Parsing meta tags from https://github.com?go-get=1 (status code 200)
go get github.com/RadhiFadlillah/qamel/qamel: no matching versions for query "latest"
```

With the second command, which I assume is because the first one failed, though, I get:

```
# github.com/RadhiFadlillah/qamel
application.cpp:2:10: fatal error: QApplication: No such file or directory
 #include <QApplication>
          ^~~~~~~~~~~~~~
compilation terminated.
```

Thanks,
-MH

**Comment by fcying** [comment]
try `go get -u -v github.com/RadhiFadlillah/qamel/cmd/qamel`

**Comment by MostHated** [comment]
:+1: Yup, that did the trick. Both of the install commands ran now. Thanks, I do appreciate it.

**Comment by MostHated** [comment]
I can't seem to build though:

```
qamel build -p linux                                                                    
Starting build process.

Load config file...done
Failed to access qamel: source directory doesn't exist
```

I am in a folder with my main.go, which also has an res folder which contains main.qml, the code in the files are just the example ones you had posted. From that root directory that contains main.go I tried to run ```qamel build -p linux    ``` 

Did I miss something by chance?

My dir is this:
~/_dev/programming/go/src/github.com/instance-id/GoUI2/guis/qt/qamel/main.go

with my gopath being ~/_dev/programming/go

**Comment by fcying** [comment]
use `go mod`.
```
fcying@lin:~ $ cp -rf ~/go/src/github.com/RadhiFadlillah/qamel/examples/hello-world ~
fcying@lin:~ $ cd ~/hello-world

fcying@lin:~/hello-world $ qamel build                                  
Starting build process.

Load config file...done
Failed to access qamel: source directory doesn't exist

fcying@lin:~/hello-world $ go mod init main                                      
go: creating new go.mod: module main
fcying@lin:~/hello-world $ qamel build
Starting build process.

Load config file...done
Generating vendor files...done
Removing old build files...done
Generating binding files...done
Generating Qt resource file...done
Generating code for QML objects...done
Building app...done
```

**Comment by MostHated** [comment]
Ok, that worked. Was finally able to get it going. Much appreciated.

Side question, my application I want to make is more of a background application that is to run as a system tray type deal but will have a few config windows that will come up when selected from the tray icon. Does this package have anything to accommodate such a setup by chance?

**Comment by fcying** [comment]
test `https://github.com/getlantern/systray`?

Similar functions in qml is `systemtrayicon`, But I have never used it, you can try it.

**Comment by MostHated** [comment]
That is the one I was using originally. I tried to use it with therecipe/qt but kept having issues until I came across widgets.QSystemTrayIcon which lead me to search more on that and I found some examples and was able to make it run on the tray. I didn't know if this package had some of the same functionality or not.

**Comment by fcying** [comment]
Similar functions in qml is `systemtrayicon`, But I have never used it in this package, you can try it.

If it don't have this feature, you can send a PR~_~

**Comment by RadhiFadlillah** [comment]
Hi guys. Yep, the documentation need to be updated, I will fix it later.

@MostHated I can confirm the [SystemTrayIcon](https://doc.qt.io/qt-5/qml-qt-labs-platform-systemtrayicon.htm) works with Qamel, at least in Linux.

**Comment by MostHated** [comment]
Great news, thanks!

**Comment by RadhiFadlillah** [comment]
Hi guys, 

I've already updated installation wiki and [fixed](https://github.com/RadhiFadlillah/qamel/commit/2d6a9ee5be1742eb45876591277ef5e8890fcb25#diff-aa1eb36f305e8271787c49177273c4a8) the issue where `qamel build` failed when ran inside `$GOPATH`. So, I will close this issue.

Feel free to reopen it if the problem still exists.
