### ISSUE TITLE
Slide menu?

### ISSUE THREAD

**Issue by MostHated** [RadhiFadlillah/qamel#13]
Hey there,
    I like what this can do so far and am excited to use it. I didn't see anything similar in this demo, but are the slide out menus able to be used in this package? I know qamel said it was simple, but not sure if that means that things like slide menus were not able to be used or not.

Thanks,
-MH

**Comment by RadhiFadlillah** [comment]
Since it seems there are no problem anymore, I will close this issue. Feels free to reopen it if needed.
