### ISSUE TITLE
internal/cmd/root.go:17:26: too many arguments in call to gap.NewScope

### ISSUE THREAD

**Issue by sh1luo** [RadhiFadlillah/qamel#24]
after downloading qamel,run `go get -u -v github.com /go-qamel/qamel/cmd/qamel`,

throw an error:

internal/cmd/root.go:17:26: too many arguments in call to gap.NewScope
     have (gap.ScopeType, string, string)
     want (gap.ScopeType,string)

OS: Manjaro 19.0.2 Kyria
Kernel: x86_64 Linux 5.5.8-1-MANJARO

**Comment by xaduha** [comment]
@sh1luo 

`userScope := ap.NewVendorScope(ap.User, "qamel", "qamel")`

fixed it for me.

**Comment by sh1luo** [comment]
I want to know why do I still have this bug with go mod because of version inconsistencies?

**Comment by sh1luo** [comment]
But i have fixed it, just review and merge branches :)

**Comment by ggymm** [comment]
try this repo https://github.com/gongym12138/qamel
i merge @sh1luo pull request 
just replace [go get -u -v github.com/go-qamel/qamel/cmd/qamel] to [go get -u -v github.com/gongym12138/qamel/cmd/qamel]
