### ISSUE TITLE
too many arguments in call to gap.NewScope

### ISSUE THREAD

**Issue by gabrielmajaron** [RadhiFadlillah/qamel#27]
Hello! trying to run go get -u -v github.com/go-qamel/qamel/cmd/qamel I get this:
go get -u -v github.com/go-qamel/qamel/cmd/qamel
github.com/go-qamel/qamel (download)
github.com/fatih/color (download)
github.com/muesli/go-app-paths (download)
github.com/mitchellh/go-homedir (download)
github.com/spf13/cobra (download)
github.com/inconshreveable/mousetrap (download)
github.com/spf13/pflag (download)
github.com/fatih/color/vendor/github.com/mattn/go-isatty
github.com/inconshreveable/mousetrap
github.com/go-qamel/qamel/internal/config
github.com/mitchellh/go-homedir
github.com/spf13/pflag
github.com/muesli/go-app-paths
github.com/fatih/color/vendor/github.com/mattn/go-colorable
github.com/go-qamel/qamel/internal/generator
github.com/fatih/color
github.com/spf13/cobra
github.com/go-qamel/qamel/internal/cmd
# github.com/go-qamel/qamel/internal/cmd

C:\Users\gabri\go\src\github.com\go-qamel\qamel\internal\cmd\root.go:17:26: too many arguments in call to gap.NewScope
        have (gap.ScopeType, string, string)
        want (gap.ScopeType, string)

thanks in advance

**Comment by ggymm** [comment]
try this repo https://github.com/gongym12138/qamel 
i fix this bug

**Comment by jcpconecomp** [comment]
I encountered the same problem in Ubuntu & Opensuse 
Replacing: 
   go get -u -v github.com/go-qamel/qamel/cmd/qamel
with:
   go get -u -v github.com/gongym12138/qamel/cmd/qamel
successfully downloaded
github.com/gongym12138/qamel (download)
github.com/fatih/color (download)
github.com/muesli/go-app-paths (download)
github.com/mitchellh/go-homedir (download)
github.com/spf13/cobra (download)
github.com/spf13/pflag (download)
github.com/gongym12138/qamel/internal/config
github.com/gongym12138/qamel/internal/generator
github.com/gongym12138/qamel/internal/cmd
github.com/gongym12138/qamel/cmd/qamel

But both:
   go get -u -d -v github.com/gongym12138/qamel
and 
   go get -u -d -v github.com/go-qamel/qamel
resulted in:
github.com/gongym12138/qamel (download)
github.com/fsnotify/fsnotify (download)
get "golang.org/x/sys/unix": found meta tag get.metaImport{Prefix:"golang.org/x/sys", VCS:"git", RepoRoot:"https://go.googlesource.com/sys"} at //golang.org/x/sys/unix?go-get=1
get "golang.org/x/sys/unix": verifying non-authoritative meta tag
golang.org/x/sys (download)
get "golang.org/x/sys/internal/unsafeheader": found meta tag get.metaImport{Prefix:"golang.org/x/sys", VCS:"git", RepoRoot:"https://go.googlesource.com/sys"} at //golang.org/x/sys/internal/unsafeheader?go-get=1
get "golang.org/x/sys/internal/unsafeheader": verifying non-authoritative meta tag
github.com/sirupsen/logrus (download)

Any suggestons would be appreciated.

**Comment by JokerQyou** [comment]
> try this repo https://github.com/gongym12138/qamel
> i fix this bug

Actually there is no need to replace all repository name with your own, that would make it very difficult to merge the changes once you decide to create a pull request. Go module system has a `replace` mechanism to simplify the fork-test-PR-merge workflow. Search for "go mod replace" for details.
