### ISSUE TITLE
build failed, like issue #15

### ISSUE THREAD

**Issue by 1369521908** [RadhiFadlillah/qamel#34]
D:\go_dev\src\go_qml>qamel build
Starting build process.

Load config file...done
Generating vendor files...done
Removing old build files...done
Generating binding files...done
Generating Qt resource file...done
Generating syso file...icon file doesn't exist
Generating code for QML objects...done
Building app...
Failed to build app: exit status 2
# github.com/go-qamel/qamel
application.cpp:2:10: fatal error: QApplication: No such file or directory
 #include <QApplication>
          ^~~~~~~~~~~~~~
compilation terminated.

D:\go_dev\src\go_qml>go env
set GO111MODULE=on
set GOARCH=amd64
set GOBIN=
set GOCACHE=C:\Users\Destiny_Xue\AppData\Local\go-build
set GOENV=C:\Users\Destiny_Xue\AppData\Roaming\go\env
set GOEXE=.exe
set GOFLAGS= -mod=
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GOINSECURE=
set GONOPROXY=
set GONOSUMDB=
set GOOS=windows
set GOPATH=D:\goproject
set GOPRIVATE=
set GOPROXY=https://goproxy.io
set GOROOT=D:\Go
set GOSUMDB=sum.golang.org
set GOTMPDIR=
set GOTOOLDIR=D:\Go\pkg\tool\windows_amd64
set GCCGO=gccgo
set AR=ar
set CC=gcc
set CXX=g++
set CGO_ENABLED=1
set GOMOD=D:\go_dev\src\go_qml\go.mod
set CGO_CFLAGS=-g -O2
set CGO_CPPFLAGS=
set CGO_CXXFLAGS=-g -O2
set CGO_FFLAGS=-g -O2
set CGO_LDFLAGS=-g -O2
set PKG_CONFIG=pkg-config
set GOGCCFLAGS=-m64 -mthreads -fmessage-length=0 -fdebug-prefix-map=C:\Users\DESTIN~1\AppData\Local\Temp\
go-build459187446=/tmp/go-build -gno-record-gcc-switches

D:\go_dev\src\go_qml>qamel profile print
Details of profile default
OS      : windows
Arch    : amd64
Static  : false
Qmake   : D:\Qt\Qt5.14.2\5.14.2\mingw73_64\bin\qmake.exe
Moc     : D:\Qt\Qt5.14.2\5.14.2\mingw73_64\bin\moc.exe
Rcc     : D:\Qt\Qt5.14.2\5.14.2\mingw73_64\bin\rcc.exe
Gcc     : D:\Qt\Qt5.14.2\Tools\mingw730_64\bin\gcc.exe
G++     : D:\Qt\Qt5.14.2\Tools\mingw730_64\bin\g++.exe
Objdump : D:\Qt\Qt5.14.2\Tools\mingw730_64\bin\objdump.exe
Windres : D:\Qt\Qt5.14.2\Tools\mingw730_64\bin\windres.exe

D:\go_dev\src\go_qml>

**Comment by 1369521908** [comment]
using go mod to dev

**Comment by makerinchina-iot** [comment]
maybe you can try to use cmder for the terminal: [](https://github.com/go-qamel/qamel/issues/18)

**Comment by 1369521908** [comment]
but how could i use the commend on windows? could you please show me how to do ? plzz~哭 伤心 大哭 不开心 流泪 桑心

**Comment by 1369521908** [comment]
opps... put the wrong button....
